name: Upload builds to release

on: [push]

jobs:
  build-evaltools:
    name: Build and upload amd64 evaltools
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - uses: iffy/install-nim@v4.1.1
      - name: Install x11 dev libraries
        run: sudo apt install libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libgl-dev build-essential
      - name: Build EvalTools
        run: |
          nimble install -y arraymancer argParse suru
	  nim c --gc:orc -d:release fast_process.nim
      - name: Upload release binaries
        uses: alexellis/upload-assets@0.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["fast_process"]'
